#!/usr/bin/env bash

# network tray icon (harmless no-op if a session has no systray)
nm-applet &

# vbox foo
vbox=$(dmesg |grep -io virtualbox)
if [ ! -z "$vbox" ]
then
  /usr/bin/VBoxClient --seamless
  /usr/bin/VBoxClient --clipboard
  /usr/bin/VBoxClient --vmsvga
fi

# wallpaper
exec feh --bg-scale /usr/share/blackarch/wallpaper.jpg &

